Repository sahilprasad-in/Tester-P1, pull requests merged in 2024-10, with the labels that each got.

#1 Updated
  Tester.sol
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#2 Update README.md
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#3 Update Ballot_test.sol
  tests/Ballot_test.sol
Labels: bug, enhancement, hacktoberfest-accepted
